# Generated by Django 2.1.7 on 2019-05-28 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='academyinfo',
            table='academies',
        ),
        migrations.AlterModelTable(
            name='classinfo',
            table='classes',
        ),
        migrations.AlterModelTable(
            name='collegeinfo',
            table='colleges',
        ),
        migrations.AlterModelTable(
            name='gradeinfo',
            table='grades',
        ),
        migrations.AlterModelTable(
            name='majorinfo',
            table='majors',
        ),
        migrations.AlterModelTable(
            name='studentinfo',
            table='students',
        ),
    ]
