# Generated by Django 2.1.7 on 2019-05-28 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0002_auto_20190528_2341'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='academyinfo',
            table='colleges_academies',
        ),
        migrations.AlterModelTable(
            name='classinfo',
            table='colleges_classes',
        ),
        migrations.AlterModelTable(
            name='gradeinfo',
            table='colleges_grades',
        ),
        migrations.AlterModelTable(
            name='majorinfo',
            table='colleges_majors',
        ),
        migrations.AlterModelTable(
            name='studentinfo',
            table='colleges_students',
        ),
    ]
