# Generated by Django 2.1.7 on 2019-06-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0003_auto_20190528_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classinfo',
            name='classId',
            field=models.BigIntegerField(unique=True, verbose_name='班级编号'),
        ),
        migrations.AlterField(
            model_name='collegeinfo',
            name='level',
            field=models.IntegerField(choices=[(1, '双一流'), (2, '一本'), (3, '二本'), (4, '三本'), (5, '专科')], null=True, verbose_name='学校级别'),
        ),
        migrations.AlterField(
            model_name='gradeinfo',
            name='gradeId',
            field=models.BigIntegerField(unique=True, verbose_name='年级编号'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='studentId',
            field=models.BigIntegerField(unique=True, verbose_name='学号'),
        ),
    ]
