# Generated by Django 2.1.7 on 2019-06-05 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0005_auto_20190605_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='year_in_college',
            field=models.IntegerField(verbose_name='入学年份'),
        ),
    ]
